- CMakeLists.txt
- extensions/standard/random.cpp
- extensions/standard/random.hpp
- extensions/standard/stdio.cpp
- extensions/standard/times.cpp
- extensions/standard/times.hpp
- interpreter/interpreter.cpp
- interpreter/interpreter.hpp
- interpreter/lamina.hpp
- interpreter/value.hpp
> 实现随机库，时间库，实现全局变量添加，修复一些BUG

- CMakeLists.txt
- interpreter/interpreter.cpp
- interpreter/interpreter.hpp
- interpreter/lamina.hpp
实现linux下so动态库加载，但是并不完善，仍有BUG，并修改了CMAKE配置，降低版本要求到3.16.3
> 实现linux下so动态库加载

- CMakeLists.txt
- extensions/standard/sockets.cpp
- extensions/standard/sockets.hpp
- extensions/type/type.cpp
- extensions/type/type.hpp
- interpreter/examples/type.lm
- interpreter/interpreter.hpp
> 实现类型库，修改CMakeLists

- CMakeLists.txt
- extensions/standard/stdio.cpp
如题，我在STDIO实现了file_put_content和file_get_content
> 手动解决冲突，实现文件操作

- extensions/ultra_minimal/CMakeLists.txt
- extensions/ultra_minimal/ultra_minimal.cpp
- interpreter/main.cpp
- interpreter/parser.cpp
> Clean Comment

- interpreter/repl_input.cpp
> 更新repl_input.cpp

- interpreter/lamina.hpp
在LAMINA_FUNC宏中的函数前添加inline关键字
c++中，在头文件中定义的函数会导致潜在的ODR问题，即如果函数在头文件中定义，且该头文件被多个 .cpp 文件包含，则每个 .cpp 文件都会生成该函数的一个定义。从而导致链接错误。
使用inline关键字可以避免该问题。
```bash
```
---
> add inline for LAMINA_FUNC series macro

- .gitmodules
- CMakeLists.txt
- extensions/standard/latex.hpp
- extensions/standard/math.cpp
本PR感谢 @hejialincn 
添加了Latex计算器和ExprTK
本PR跟 #16 略有联系
```bash
./Lamina
init();
set_var("a", 10);
calculate(); # 表达式省略
```
Lamina REPL. Press Ctrl+C or :exit to exit.
Type :help for help.
> init();
> set_var("a", 10);
> calculate 
Error: Missing semicolon ';' after expression statement
> calculate("!23123");
ERROR: Exception in expression statement: LaTeX evaluation failed: Compilation error: ERR248 - Premature end of expression[2] # 故意尝试错误表达式
---
> 有关于Latex Calculator的实现

- interpreter/repl_input.cpp
1. 为了减小代码耦合度，我在 `repl_input.cpp` 中添加了 `CtrlCExit()` 函数；
2. 为了使 `CtrlCExit()` 正确获得 `oldt` 的值，我将 `oldt` 设为全局变量（仅在非 Windows 时）；
2. 使用 signal() 捕捉 SIGINT 信号，触发时调用 `CtrlCExit()`. **(重点)**
在一般的环境中，按下 Ctrl + C 会向程序发送 SIGINT 信号，然后退出，所以无法经过下面这几行代码以抛出异常
https://github.com/Lamina-dev/Lamina/blob/c2003c7cb82c065a51f3bd7f9e3b3cc4b04a8069/interpreter/repl_input.cpp#L241-L245
所以按下 Ctrl+C 时，就会得到这种情况: 
```
$  ./Lamina
Lamina REPL. Press Ctrl+C or :exit to exit.
Type :help for help.
> ⏎
（程序返回值为 130，而非正常的 0，并且没有输出期望的 ^C）
```
none
```bash
```
---
（我删除了默认 PR 内容的一些不相关的项）
> 修复了非 Windows 下运行 repl 时 Ctrl+C 不会正常退出的情况

- CMakeLists.txt
- extensions/standard/latex.hpp
- extensions/standard/math.cpp
> 优化MINGW在编译时的速度

- .gitignore
- xmake.lua
支持xmake作为构建系统
支持xmake作为构建系统
```bash
```
---
> [Feature] basic support for xmake

- interpreter/interpreter.cpp
修改`interpreter/interpreter.cpp`中的`Interpreter::eval()`函数处理user-defined function
s的部分。
在原先执行user-defined functions时，程序先创建函数的变量作用域，再解析变量，以至于当函数嵌套另一个函数时变量的值可能出错，详见#40。
- Closes #40 
```bash
func A(x, y) {
if (y == 0) { return 0; }
if (x == 0) { return 2 * y; } 
if (y == 1) { return 2;}
return A(x - 1, A(x, y - 1));
}
print(A(3, 3));
./Lamina test.lm
```
输出：
`65536`
---
> [Bug Fix] 修复函数嵌套问题

- .github/workflows/issue_management.yml
- .github/workflows/quality.yml
使用 peter-evans/create-or-update-comment@v4 来议题和拉取请求的评论。
这样有更可读的代码。
`.github/workflows/quality.yml` 被自动格式化了，没办法，插件自动行为（prettier），可以忽略一下空白字符再 diff。
修复以下问题：
```bash
```
---
> [ci] 使用 peter-evans/create-or-update-comment@v4 来添加评论

- extensions/standard/math.cpp
给math子模块增加一大堆注释
```bash
```
---
> [Feature][math]给math子模块增加注释

- xmake.lua
> fix: fix build on Termux

- CMakeLists.txt
在CmakeLists.txt中使用了CMAKE_INSTALL_LIBDIR变量来实现了各个平台自适应的安装路径
内容：更改了CmakeLists.txt文件中执行make install时读取的安装目录，将lib改为了${CMAKE_INSTALL_LIBDIR}
原因：issues #47 
- Closes #47 
```bash
emerge -a dev-lang/Lamina
Lamina
```
成功使用我所写的Ebuild安装了Lamina，并加入了全局PATH变量中的文件夹里，可以全局调用Lamina解释器
第一次提交，如果做的不对轻点骂（
---
> 为CmakeLists.txt文件添加CMAKE_INSTALL_LIBDIR变量来实现各个平台自适应的安装路径

- docs/zh_CN/Compile.md
As the title reads
zh_CN/Compile.md is different from en_US's
Just compile it
```bash
```
---
> Sync from en_US/Compile.md

- interpreter/interpreter.cpp
修改`interpreter/interpreter.cpp`中bigint的%和^两种运算。
在bigint实现了取模和幂运算后，解释时仍然先转化为int进行计算导致出现问题
- Closes #118 
```bash
./Lamina
print(13316161643433461916464646646 % 2);
print(31316131313131313313113131313311331 ^ 2);
```
计算结果正确
---
> [BugFix] 修复bigint运算

- interpreter/console_ui.cpp
- interpreter/interpreter.cpp
- interpreter/symbolic.cpp
- interpreter/value.hpp
1. 添加负小数字面量支持（解决 #116）。
2. 添加向量减法支持（解决 #115）。
3. 勉强绕过了 Github Actions 里面 Windows build 的那个奇怪问题。
- Related to #115 and #116。
```bash
```
性能影响：`-` 也变成了需要单独判断的运算符。
---
> 终于有正常的 `-` 了

- .github/workflows/quality.yml
> [BugFix] 修复Actions问题

- .github/workflows/comment_pr.yml
- .github/workflows/quality.yml
- interpreter/bigint.hpp
修改`/.github/workflows/quality.yml`
在`quality.yml`中加入检测`.hpp.in`文件变更
添加`issue: write`权限以解决错误
在bigint.hpp中加入一个空行，以触发Comment On PR，测试问题是否解决
```bash
```
---
> [BugFix] 修复Comment on PR问题

- xmake.lua
> fix: fix xmake.lua

- interpreter/eval.cpp
把`eval_BinaryExpr`函数中对加号的处理独立
```bash
```
---
> 更新: 独立的BINARY_ADD

- interpreter/symbolic.cpp
- interpreter/symbolic.hpp
避免乘法陷入无限循环。
- Closes #126
- Closes #163
测试了上述两个 issue 中提到的代码。
每次乘法前都将检查是否化简，可能有一定性能影响。
---
> 紧急解决 SymbolicExpr 问题
